const data = {
  productos: [
    {
      id: 1,
      nombre: "FIFA 21",
      slug: "FIFA 21",
      etiqueta: "Futbol",
      categoria: "Deporte",
      image: "/images/Fifa21.jpg",
      precio: 45,
      stock: 10,
      rating: 4.5,
      numVista: 10,
      descripcion: "Es el mejor juego de futbol para compartir entre todos ",
    },
    {
      id: 2,
      nombre: "Grand The Auto V",
      slug: "Grand The Auto V",
      etiqueta: "Action",
      categoria: "Mundo Abierto",
      image: "/images/gtav.jpg",
      precio: 60,
      stock: 14,
      rating: 4.5,
      numVista: 10,
      descripcion:
        "Juego de mundo abierto , donde puedes disfrutar de nuevos retos junto a tus amigos",
    },
    {
      id: 3,
      nombre: "Spiderman",
      slug: "Spiderman",
      etiqueta: "Action",
      categoria: "Mundo Abierto",
      image: "/images/spiderman.png",
      precio: 55,
      stock: 14,
      rating: 4.5,
      numVista: 10,
      descripcion:
        "Un juego de mundo abierto donde exploras el mundo de Peter Parker y Max Morales",
    },
    {
      id: 4,
      nombre: "God Of War IV",
      slug: "God Of War IV",
      etiqueta: "Action",
      categoria: "Mundo Abierto",
      image: "/images/GodOfWar1.jpg",
      precio: 60,
      stock: 14,
      rating: 4.5,
      numVista: 10,
      descripcion:
        "En un mundo nordico , Kratos ira descubriendo el nuevo mundo y afrontar los nuevos retos ademas de hacer frente a su pasado",
    },
  ],
};
export default data;
